version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10-stretch
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    steps:
      - checkout
      - restore_cache:
          key: npm-caches-{{ checksum "module/package.json" }}
      - run: cd module && npm install
      - save_cache:
          key: npm-caches-{{ checksum "module/package.json" }}
          paths:
            - module/node_modules
            - module/package-lock.json
      - run: cd module && dockerize -wait tcp://localhost:9200 npm run test
  release:
    parameters:
      image:
        type: string
        description: The name of the docker image to push to.
      tag:
        type: string
        default: latest
        description: The docker tag to use
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -t "<< parameters.image >>:<< parameters.tag >>"
      - run: docker push "<< parameters.image >>:<< parameters.tag >>"

workflows:
  test_release:
    jobs:
      - test
      - release:
          image: rbayliss/filebeat-acquia
          tag: latest
          context: org-global
          requires: [test]
          filters:
            tags: {ignore: /.*/}
            branches: {only: master}
  release:
    jobs:
      - release:
          image: rbayliss/filebeat-acquia
          tag: $CIRCLE_TAG
          context: org-global
          filters:
            tags: {only: /.*/}
            branches: {ignore: /.*/}
