version: 2.1

jobs:
  test:
    docker:
      - image: node:9
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "module/package.json" }}
      - run: cd module && npm install
      - save_cache:
          key: npm-cache-{{ checksum "module/package.json" }}
          paths:
            - module/node_modules
            - module/package-lock.json
      - run: cd module && npm run test

workflows:
  test:
    jobs:
      - test